### ISSUE TITLE
Error with when downloading images

### ISSUE THREAD

**Issue by icaoberg** [murphygroup/cellorganizer-python#3]
I made a notebook that has been included in the image in Dockerhub.

The notebook tries to download the images using the method you created

![screenshot 2019-02-05 01 32 00](https://user-images.githubusercontent.com/413752/52256928-94781e80-28e6-11e9-8580-e12e3c8ded78.png)

but fails

![screenshot 2019-02-05 00 58 19](https://user-images.githubusercontent.com/413752/52257008-f3d62e80-28e6-11e9-9463-50b8378d301c.png)

If you take a look, it assumes the tarball existing in `~/images` but it exists in `~/`.

**Comment by asankar** [comment]
Pushed fix of typo
