### ISSUE TITLE
Download method still broken

### ISSUE THREAD

**Issue by icaoberg** [murphygroup/cellorganizer-python#6]
It deletes the file in the `~/` but keeps the file in `~/images/`

![screenshot 2019-02-05 12 02 57](https://user-images.githubusercontent.com/413752/52290438-12b3df80-293e-11e9-9c3f-0ca2ddc8774f.png)

**Comment by icaoberg** [comment]
Wait no....

![screenshot 2019-02-05 12 04 25](https://user-images.githubusercontent.com/413752/52290556-48f15f00-293e-11e9-9a65-9e51072e61bc.png)

**Comment by asankar** [comment]
Sorry same typo in murphy lab misspelling that I missed. I can fix it really quick
